"""指标口径词典：概念级的"这个指标怎么算的"说明。
用途：回答"皮层厚度是左右平均还是单侧""侧脑室体积怎么算""孕龄缺失算不算"这类
【查定义而非查数值】的问题——SQL 答不了，靠语义层直接答。也是防幻觉的一环(口径先对齐)。"""

GLOSSARY = [
 {"term":"皮层厚度","aliases":["皮层","皮质厚度","cortical thickness"],"unit":"mm",
  "columns":["cortical_thickness_mean_left_mm","cortical_thickness_mean_right_mm"],
  "口径":"分左、右两列，均为该侧皮层的平均厚度；库内无'左右总平均'列，如需总体厚度请自行对左右取均值。"},
 {"term":"小脑体积","aliases":["小脑"],"unit":"ml",
  "columns":["cerebellum_left_volume_ml","cerebellum_right_volume_ml"],
  "口径":"分左、右两列；'小脑总体积'需将左+右相加。未指明左右时通常指总体积(左+右)。"},
 {"term":"大脑体积","aliases":["大脑","脑子大小","脑体积"],"unit":"ml",
  "columns":["cerebrum_left_volume_ml","cerebrum_right_volume_ml"],
  "口径":"分左、右两列；总体积=左+右。注意与'小脑'区分。"},
 {"term":"侧脑室体积","aliases":["侧脑室","脑室大小","脑积水","脑室扩张"],"unit":"ml",
  "columns":["lateral_ventricle_left_volume_ml","lateral_ventricle_right_volume_ml"],
  "口径":"分左、右两列；总体积=左+右。侧脑室偏大常用于评估脑室扩张风险。"},
 {"term":"第三脑室/第四脑室体积","aliases":["第三脑室","第四脑室","三四脑室"],"unit":"ml",
  "columns":["third_ventricle_volume_ml","fourth_ventricle_volume_ml"],
  "口径":"各为单列(不分左右)，单位 ml。"},
 {"term":"表面积","aliases":["软膜表面积","白质表面积","surface area"],"unit":"mm2",
  "columns":["pial_surface_area_left_mm2","pial_surface_area_right_mm2","white_surface_area_left_mm2","white_surface_area_right_mm2"],
  "口径":"分软膜(pial)与白质(white)两种，各再分左右，单位 mm²。"},
 {"term":"孕龄","aliases":["孕周","胎龄","GA","孕龄大小"],"unit":"周",
  "columns":["gestational_age","age_known"],
  "口径":"单位周。约 564 例个体原始无孕龄记录(age_known=0)；涉及孕龄的统计默认用 age_known=1 过滤、排除这些个体，并应在结果中说明排除了多少。"},
 {"term":"半球不对称指数","aliases":["不对称","左右不对称","asymmetry"],"unit":"",
  "columns":["cerebrum_volume_hemispheric_asymmetry_index"],
  "口径":"衡量大脑体积左右半球不对称程度的指数；值越大越不对称。"},
 {"term":"分形维数(FD)","aliases":["分形维数","FD","分形"],"unit":"",
  "columns":["FD_tissue_*(组织级19项)","FD_roi_*(精细脑区级124项)"],
  "口径":"反映结构复杂度的指标，分组织级(FD_tissue_)与精细脑区级(FD_roi_)，列名含中文脑区名(如 FD_roi_055_左梭状回)。查具体脑区请配合 lookup_columns。"},
 {"term":"模态/序列","aliases":["模态","序列","haste","trufi","btfe"],"unit":"",
  "columns":["modality"],
  "口径":"MRI 采集序列类型(haste/trufi/btfe)，由影像文件名解析得到；解析不出的标为'未知'。"},
 {"term":"中心/来源","aliases":["中心","来源","医院"],"unit":"",
  "columns":["center"],
  "口径":"数据来源中心，归一为 广州/华西/四川/未标注中心(自重建批)。'未标注'为自重建批次、原始未标中心。"},
 {"term":"分割状态","aliases":["有分割","是否分割","分割"],"unit":"",
  "columns":[],
  "口径":"本库收录的个体均已完成脑分割并提取了形态学特征，即库内群体=可分析群体；'某中心收了多少例'与'某中心可分析多少例'可能是两个数。"},
]
